from enum import StrEnum


class CompanyType(StrEnum):
    GENERAL_NON_FINANCIAL = "GENERAL_NON_FINANCIAL"
    MATURE_NON_FINANCIAL = "MATURE_NON_FINANCIAL"
    FINANCIAL = "FINANCIAL"
    PRE_REVENUE_BIOTECH = "PRE_REVENUE_BIOTECH"
    HIGH_GROWTH_PLATFORM = "HIGH_GROWTH_PLATFORM"
    DISTRESSED = "DISTRESSED"


class LifeCycleStage(StrEnum):
    PRE_REVENUE = "PRE_REVENUE"
    EARLY_GROWTH = "EARLY_GROWTH"
    HIGH_GROWTH = "HIGH_GROWTH"
    MATURE_GROWTH = "MATURE_GROWTH"
    STABLE = "STABLE"
    DECLINE = "DECLINE"
